name: BuildTV

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Allow wrapper
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew assembleRelease
      - name: Export APK
        run: mkdir -p out && cp app/build/outputs/apk/release/app-release.apk out/
